/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSheetModeRouteImport } from './routes/_authenticated/sheet-mode'
import { Route as AuthenticatedSheetRouteImport } from './routes/_authenticated/sheet'
import { Route as AuthenticatedReelFormulaRouteImport } from './routes/_authenticated/reel-formula'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGlobalDashboardRouteImport } from './routes/_authenticated/global-dashboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsSchedulerRouteImport } from './routes/_authenticated/settings/scheduler'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsBufferRouteImport } from './routes/_authenticated/settings/buffer'
import { Route as AuthenticatedSettingsAnalysisRouteImport } from './routes/_authenticated/settings/analysis'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron/tick'
import { Route as ApiPublicCronRecoverStaleRouteImport } from './routes/api/public/cron/recover-stale'
import { Route as ApiPublicCronFetchAnalyticsRouteImport } from './routes/api/public/cron/fetch-analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSheetModeRoute = AuthenticatedSheetModeRouteImport.update({
  id: '/sheet-mode',
  path: '/sheet-mode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSheetRoute = AuthenticatedSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelFormulaRoute =
  AuthenticatedReelFormulaRouteImport.update({
    id: '/reel-formula',
    path: '/reel-formula',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGlobalDashboardRoute =
  AuthenticatedGlobalDashboardRouteImport.update({
    id: '/global-dashboard',
    path: '/global-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSchedulerRoute =
  AuthenticatedSettingsSchedulerRouteImport.update({
    id: '/settings/scheduler',
    path: '/settings/scheduler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBufferRoute =
  AuthenticatedSettingsBufferRouteImport.update({
    id: '/settings/buffer',
    path: '/settings/buffer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAnalysisRoute =
  AuthenticatedSettingsAnalysisRouteImport.update({
    id: '/settings/analysis',
    path: '/settings/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRecoverStaleRoute =
  ApiPublicCronRecoverStaleRouteImport.update({
    id: '/api/public/cron/recover-stale',
    path: '/api/public/cron/recover-stale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFetchAnalyticsRoute =
  ApiPublicCronFetchAnalyticsRouteImport.update({
    id: '/api/public/cron/fetch-analytics',
    path: '/api/public/cron/fetch-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reel-formula': typeof AuthenticatedReelFormulaRoute
  '/sheet': typeof AuthenticatedSheetRoute
  '/sheet-mode': typeof AuthenticatedSheetModeRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/analysis': typeof AuthenticatedSettingsAnalysisRoute
  '/settings/buffer': typeof AuthenticatedSettingsBufferRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/fetch-analytics': typeof ApiPublicCronFetchAnalyticsRoute
  '/api/public/cron/recover-stale': typeof ApiPublicCronRecoverStaleRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reel-formula': typeof AuthenticatedReelFormulaRoute
  '/sheet': typeof AuthenticatedSheetRoute
  '/sheet-mode': typeof AuthenticatedSheetModeRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/analysis': typeof AuthenticatedSettingsAnalysisRoute
  '/settings/buffer': typeof AuthenticatedSettingsBufferRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/fetch-analytics': typeof ApiPublicCronFetchAnalyticsRoute
  '/api/public/cron/recover-stale': typeof ApiPublicCronRecoverStaleRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/global-dashboard': typeof AuthenticatedGlobalDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/reel-formula': typeof AuthenticatedReelFormulaRoute
  '/_authenticated/sheet': typeof AuthenticatedSheetRoute
  '/_authenticated/sheet-mode': typeof AuthenticatedSheetModeRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/analysis': typeof AuthenticatedSettingsAnalysisRoute
  '/_authenticated/settings/buffer': typeof AuthenticatedSettingsBufferRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/scheduler': typeof AuthenticatedSettingsSchedulerRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/fetch-analytics': typeof ApiPublicCronFetchAnalyticsRoute
  '/api/public/cron/recover-stale': typeof ApiPublicCronRecoverStaleRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/global-dashboard'
    | '/insights'
    | '/learning'
    | '/queue'
    | '/reel-formula'
    | '/sheet'
    | '/sheet-mode'
    | '/settings/ai'
    | '/settings/analysis'
    | '/settings/buffer'
    | '/settings/general'
    | '/settings/scheduler'
    | '/settings/'
    | '/api/public/cron/fetch-analytics'
    | '/api/public/cron/recover-stale'
    | '/api/public/cron/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/global-dashboard'
    | '/insights'
    | '/learning'
    | '/queue'
    | '/reel-formula'
    | '/sheet'
    | '/sheet-mode'
    | '/settings/ai'
    | '/settings/analysis'
    | '/settings/buffer'
    | '/settings/general'
    | '/settings/scheduler'
    | '/settings'
    | '/api/public/cron/fetch-analytics'
    | '/api/public/cron/recover-stale'
    | '/api/public/cron/tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/dashboard'
    | '/_authenticated/global-dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/learning'
    | '/_authenticated/queue'
    | '/_authenticated/reel-formula'
    | '/_authenticated/sheet'
    | '/_authenticated/sheet-mode'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/analysis'
    | '/_authenticated/settings/buffer'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/scheduler'
    | '/_authenticated/settings/'
    | '/api/public/cron/fetch-analytics'
    | '/api/public/cron/recover-stale'
    | '/api/public/cron/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronFetchAnalyticsRoute: typeof ApiPublicCronFetchAnalyticsRoute
  ApiPublicCronRecoverStaleRoute: typeof ApiPublicCronRecoverStaleRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheet-mode': {
      id: '/_authenticated/sheet-mode'
      path: '/sheet-mode'
      fullPath: '/sheet-mode'
      preLoaderRoute: typeof AuthenticatedSheetModeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sheet': {
      id: '/_authenticated/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof AuthenticatedSheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reel-formula': {
      id: '/_authenticated/reel-formula'
      path: '/reel-formula'
      fullPath: '/reel-formula'
      preLoaderRoute: typeof AuthenticatedReelFormulaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/global-dashboard': {
      id: '/_authenticated/global-dashboard'
      path: '/global-dashboard'
      fullPath: '/global-dashboard'
      preLoaderRoute: typeof AuthenticatedGlobalDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/scheduler': {
      id: '/_authenticated/settings/scheduler'
      path: '/settings/scheduler'
      fullPath: '/settings/scheduler'
      preLoaderRoute: typeof AuthenticatedSettingsSchedulerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/buffer': {
      id: '/_authenticated/settings/buffer'
      path: '/settings/buffer'
      fullPath: '/settings/buffer'
      preLoaderRoute: typeof AuthenticatedSettingsBufferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/analysis': {
      id: '/_authenticated/settings/analysis'
      path: '/settings/analysis'
      fullPath: '/settings/analysis'
      preLoaderRoute: typeof AuthenticatedSettingsAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/recover-stale': {
      id: '/api/public/cron/recover-stale'
      path: '/api/public/cron/recover-stale'
      fullPath: '/api/public/cron/recover-stale'
      preLoaderRoute: typeof ApiPublicCronRecoverStaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fetch-analytics': {
      id: '/api/public/cron/fetch-analytics'
      path: '/api/public/cron/fetch-analytics'
      fullPath: '/api/public/cron/fetch-analytics'
      preLoaderRoute: typeof ApiPublicCronFetchAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGlobalDashboardRoute: typeof AuthenticatedGlobalDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedReelFormulaRoute: typeof AuthenticatedReelFormulaRoute
  AuthenticatedSheetRoute: typeof AuthenticatedSheetRoute
  AuthenticatedSheetModeRoute: typeof AuthenticatedSheetModeRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAnalysisRoute: typeof AuthenticatedSettingsAnalysisRoute
  AuthenticatedSettingsBufferRoute: typeof AuthenticatedSettingsBufferRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsSchedulerRoute: typeof AuthenticatedSettingsSchedulerRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGlobalDashboardRoute: AuthenticatedGlobalDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedReelFormulaRoute: AuthenticatedReelFormulaRoute,
  AuthenticatedSheetRoute: AuthenticatedSheetRoute,
  AuthenticatedSheetModeRoute: AuthenticatedSheetModeRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAnalysisRoute: AuthenticatedSettingsAnalysisRoute,
  AuthenticatedSettingsBufferRoute: AuthenticatedSettingsBufferRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsSchedulerRoute: AuthenticatedSettingsSchedulerRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronFetchAnalyticsRoute: ApiPublicCronFetchAnalyticsRoute,
  ApiPublicCronRecoverStaleRoute: ApiPublicCronRecoverStaleRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
